---
include:
  - board: nice_nano_v2
    shield: rolio_left nice_view_adapter nice_view
    artifact-name: scorpio-left-nice_view
  - board: nice_nano_v2
    shield: rolio_right nice_view_adapter nice_view
    artifact-name: scorpio-right-nice_view
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: scorpio-settings_reset
